name: Create OCI Instance

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Create .env file
        run: |
          echo "OCI_REGION=${{ secrets.OCI_REGION }}" > .env
          echo "OCI_USER_ID=${{ secrets.OCI_USER_ID }}" >> .env
          echo "OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}" >> .env
          echo "OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}" >> .env
          echo "OCI_PRIVATE_KEY_FILENAME=./oci_api_key.pem" >> .env
          echo "OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}" >> .env
          echo "OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}" >> .env
          echo "OCI_AVAILABILITY_DOMAIN=${{ secrets.OCI_AVAILABILITY_DOMAIN }}" >> .env
          echo "OCI_OCPUS=${{ secrets.OCI_OCPUS }}" >> .env
          echo "OCI_MEMORY_IN_GBS=${{ secrets.OCI_MEMORY_IN_GBS }}" >> .env
          echo "OCI_SHAPE=${{ secrets.OCI_SHAPE }}" >> .env
          echo "OCI_DISPLAY_NAME=ubuntu-ampere" >> .env

      - name: Create private key file
        run: echo "${{ secrets.OCI_PRIVATE_KEY }}" > oci_api_key.pem

      - name: Run script in loop
        run: |
          for i in 1 2 3 4 5 6 7 8 9 10; do
            php index.php
            sleep 30
          done
